modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/komikan/better-nitwit/issues"

[[mods]]
modId="better_nitwit"
displayName="Better Nitwit"
version="${mod_version}"
authors="komikan"
credits="Made with GeckoLib and NeoForge"
description='''
Adds realistic animations to Nitwit villagers including yawning, dozing off, lazy walking, sitting, and denial gestures.
Uses GeckoLib for smooth, natural animations while maintaining compatibility with other villager mods.
'''
logoFile="better_nitwit.png"

[[dependencies.better_nitwit]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.better_nitwit]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.better_nitwit]]
modId="geckolib"
type="required"
versionRange="[4.7.3,)"
ordering="NONE"
side="BOTH"